In [1]:
import numpy as np
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical


Using TensorFlow backend.
/home/berker/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/berker/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/berker/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/berker/.local/lib/python3.6/site-packages/tensorflow/python

In [2]:
df = pd.read_csv('./DataSet/hw03_images.csv')
df_label = pd.read_csv('./DataSet/hw03_labels.csv')
df.shape
df_train = df.iloc[:500]
df_test = df.iloc[500:]

In [3]:
df_label

1
0    3
1    5
2    1
3    5
4    1
..  ..
994  1
995  2
996  5
997  5
998  4

[999 rows x 1 columns]

In [4]:
def encoder(lbl, cls):
    encoded = np.zeros(shape=(lbl.shape[0],cls))
    c = 0
    print(lbl.shape)
    for i in lbl['1']:
        
        iteration = int(i)
        encoded[c][iteration-1] = 1
        c = c+1
    print(encoded, encoded.shape)
    return encoded
encoded_train = encoder(df_label.iloc[:500], 5)
encoded_test = encoder(df_label.iloc[500:], 5)

(500, 1)
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]] (500, 5)
(499, 1)
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]] (499, 5)


In [5]:
df_train.shape

(500, 784)

In [6]:
keras.optimizers.rmsprop(lr=0.0001)
df_test.shape

(499, 784)

In [7]:
model = Sequential()
model.add(Dense(20, activation='sigmoid', input_shape=(784,)))
model.add(Dense(5, activation='softmax'))
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [8]:
history = model.fit(df_train, encoded_train, batch_size=256, epochs=500, verbose=1, 
                   validation_data=(df_test, encoded_test))


Train on 500 samples, validate on 499 samples
Epoch 1/500
500/500 [==============================] - 0s 392us/step - loss: 1.7178 - accuracy: 0.1740 - val_loss: 1.5613 - val_accuracy: 0.4269
Epoch 2/500
500/500 [==============================] - 0s 22us/step - loss: 1.5364 - accuracy: 0.4080 - val_loss: 1.4949 - val_accuracy: 0.5311
Epoch 3/500
500/500 [==============================] - 0s 20us/step - loss: 1.4704 - accuracy: 0.5520 - val_loss: 1.4343 - val_accuracy: 0.4589
Epoch 4/500
500/500 [==============================] - 0s 22us/step - loss: 1.4100 - accuracy: 0.5340 - val_loss: 1.3741 - val_accuracy: 0.5711
Epoch 5/500
500/500 [==============================] - 0s 29us/step - loss: 1.3617 - accuracy: 0.5580 - val_loss: 1.3315 - val_accuracy: 0.5912
Epoch 6/500
500/500 [==============================] - 0s 19us/step - loss: 1.3172 - accuracy: 0.6320 - val_loss: 1.2850 - val_accuracy: 0.8116
Epoch 7/500
500/500 [==============================] - 0s 26us/step - loss: 1.2709 - acc

Epoch 56/500
500/500 [==============================] - 0s 19us/step - loss: 0.6156 - accuracy: 0.9080 - val_loss: 0.6041 - val_accuracy: 0.9299
Epoch 57/500
500/500 [==============================] - 0s 22us/step - loss: 0.6030 - accuracy: 0.9220 - val_loss: 0.5937 - val_accuracy: 0.9238
Epoch 58/500
500/500 [==============================] - 0s 20us/step - loss: 0.5989 - accuracy: 0.9040 - val_loss: 0.6003 - val_accuracy: 0.9238
Epoch 59/500
500/500 [==============================] - 0s 19us/step - loss: 0.5977 - accuracy: 0.9140 - val_loss: 0.5836 - val_accuracy: 0.9279
Epoch 60/500
500/500 [==============================] - 0s 20us/step - loss: 0.5859 - accuracy: 0.9080 - val_loss: 0.5783 - val_accuracy: 0.9238
Epoch 61/500
500/500 [==============================] - 0s 18us/step - loss: 0.5791 - accuracy: 0.9160 - val_loss: 0.5756 - val_accuracy: 0.9218
Epoch 62/500
500/500 [==============================] - 0s 21us/step - loss: 0.5780 - accuracy: 0.9080 - val_loss: 0.5717 - val_ac

500/500 [==============================] - 0s 19us/step - loss: 0.3608 - accuracy: 0.9380 - val_loss: 0.3624 - val_accuracy: 0.9359
Epoch 113/500
500/500 [==============================] - 0s 18us/step - loss: 0.3575 - accuracy: 0.9480 - val_loss: 0.3649 - val_accuracy: 0.9379
Epoch 114/500
500/500 [==============================] - 0s 21us/step - loss: 0.3521 - accuracy: 0.9380 - val_loss: 0.3566 - val_accuracy: 0.9339
Epoch 115/500
500/500 [==============================] - 0s 19us/step - loss: 0.3479 - accuracy: 0.9460 - val_loss: 0.3587 - val_accuracy: 0.9299
Epoch 116/500
500/500 [==============================] - 0s 22us/step - loss: 0.3485 - accuracy: 0.9420 - val_loss: 0.3616 - val_accuracy: 0.9299
Epoch 117/500
500/500 [==============================] - 0s 18us/step - loss: 0.3431 - accuracy: 0.9480 - val_loss: 0.3509 - val_accuracy: 0.9319
Epoch 118/500
500/500 [==============================] - 0s 20us/step - loss: 0.3394 - accuracy: 0.9500 - val_loss: 0.3455 - val_accuracy:

500/500 [==============================] - 0s 19us/step - loss: 0.2289 - accuracy: 0.9600 - val_loss: 0.2519 - val_accuracy: 0.9319
Epoch 169/500
500/500 [==============================] - 0s 23us/step - loss: 0.2266 - accuracy: 0.9600 - val_loss: 0.2545 - val_accuracy: 0.9319
Epoch 170/500
500/500 [==============================] - 0s 21us/step - loss: 0.2265 - accuracy: 0.9580 - val_loss: 0.2585 - val_accuracy: 0.9339
Epoch 171/500
500/500 [==============================] - 0s 18us/step - loss: 0.2249 - accuracy: 0.9560 - val_loss: 0.2481 - val_accuracy: 0.9279
Epoch 172/500
500/500 [==============================] - 0s 19us/step - loss: 0.2261 - accuracy: 0.9620 - val_loss: 0.2526 - val_accuracy: 0.9399
Epoch 173/500
500/500 [==============================] - 0s 20us/step - loss: 0.2260 - accuracy: 0.9560 - val_loss: 0.2454 - val_accuracy: 0.9319
Epoch 174/500
500/500 [==============================] - 0s 20us/step - loss: 0.2268 - accuracy: 0.9600 - val_loss: 0.2556 - val_accuracy:

500/500 [==============================] - 0s 19us/step - loss: 0.1622 - accuracy: 0.9640 - val_loss: 0.2007 - val_accuracy: 0.9359
Epoch 225/500
500/500 [==============================] - 0s 18us/step - loss: 0.1580 - accuracy: 0.9660 - val_loss: 0.2018 - val_accuracy: 0.9319
Epoch 226/500
500/500 [==============================] - 0s 17us/step - loss: 0.1591 - accuracy: 0.9640 - val_loss: 0.1990 - val_accuracy: 0.9339
Epoch 227/500
500/500 [==============================] - 0s 17us/step - loss: 0.1570 - accuracy: 0.9660 - val_loss: 0.2075 - val_accuracy: 0.9319
Epoch 228/500
500/500 [==============================] - 0s 18us/step - loss: 0.1565 - accuracy: 0.9660 - val_loss: 0.2005 - val_accuracy: 0.9339
Epoch 229/500
500/500 [==============================] - 0s 17us/step - loss: 0.1538 - accuracy: 0.9640 - val_loss: 0.1997 - val_accuracy: 0.9339
Epoch 230/500
500/500 [==============================] - 0s 17us/step - loss: 0.1575 - accuracy: 0.9640 - val_loss: 0.2000 - val_accuracy:

500/500 [==============================] - 0s 21us/step - loss: 0.1311 - accuracy: 0.9680 - val_loss: 0.1890 - val_accuracy: 0.9359
Epoch 281/500
500/500 [==============================] - 0s 18us/step - loss: 0.1205 - accuracy: 0.9720 - val_loss: 0.1773 - val_accuracy: 0.9379
Epoch 282/500
500/500 [==============================] - 0s 21us/step - loss: 0.1161 - accuracy: 0.9720 - val_loss: 0.1745 - val_accuracy: 0.9359
Epoch 283/500
500/500 [==============================] - 0s 21us/step - loss: 0.1197 - accuracy: 0.9660 - val_loss: 0.1799 - val_accuracy: 0.9339
Epoch 284/500
500/500 [==============================] - 0s 20us/step - loss: 0.1180 - accuracy: 0.9680 - val_loss: 0.1726 - val_accuracy: 0.9359
Epoch 285/500
500/500 [==============================] - 0s 19us/step - loss: 0.1159 - accuracy: 0.9720 - val_loss: 0.1745 - val_accuracy: 0.9339
Epoch 286/500
500/500 [==============================] - 0s 20us/step - loss: 0.1161 - accuracy: 0.9660 - val_loss: 0.1842 - val_accuracy:

500/500 [==============================] - 0s 22us/step - loss: 0.0898 - accuracy: 0.9760 - val_loss: 0.1622 - val_accuracy: 0.9399
Epoch 337/500
500/500 [==============================] - 0s 20us/step - loss: 0.0933 - accuracy: 0.9760 - val_loss: 0.1768 - val_accuracy: 0.9359
Epoch 338/500
500/500 [==============================] - 0s 21us/step - loss: 0.0967 - accuracy: 0.9740 - val_loss: 0.1654 - val_accuracy: 0.9379
Epoch 339/500
500/500 [==============================] - 0s 19us/step - loss: 0.0896 - accuracy: 0.9740 - val_loss: 0.1602 - val_accuracy: 0.9359
Epoch 340/500
500/500 [==============================] - 0s 18us/step - loss: 0.0892 - accuracy: 0.9760 - val_loss: 0.1620 - val_accuracy: 0.9379
Epoch 341/500
500/500 [==============================] - 0s 20us/step - loss: 0.0879 - accuracy: 0.9760 - val_loss: 0.1633 - val_accuracy: 0.9399
Epoch 342/500
500/500 [==============================] - 0s 18us/step - loss: 0.0894 - accuracy: 0.9720 - val_loss: 0.1598 - val_accuracy:

500/500 [==============================] - 0s 21us/step - loss: 0.0748 - accuracy: 0.9760 - val_loss: 0.1571 - val_accuracy: 0.9439
Epoch 393/500
500/500 [==============================] - 0s 23us/step - loss: 0.0724 - accuracy: 0.9820 - val_loss: 0.1587 - val_accuracy: 0.9399
Epoch 394/500
500/500 [==============================] - 0s 19us/step - loss: 0.0725 - accuracy: 0.9800 - val_loss: 0.1610 - val_accuracy: 0.9419
Epoch 395/500
500/500 [==============================] - 0s 22us/step - loss: 0.0729 - accuracy: 0.9800 - val_loss: 0.1678 - val_accuracy: 0.9399
Epoch 396/500
500/500 [==============================] - 0s 23us/step - loss: 0.0708 - accuracy: 0.9800 - val_loss: 0.1552 - val_accuracy: 0.9399
Epoch 397/500
500/500 [==============================] - 0s 18us/step - loss: 0.0705 - accuracy: 0.9800 - val_loss: 0.1580 - val_accuracy: 0.9399
Epoch 398/500
500/500 [==============================] - 0s 20us/step - loss: 0.0704 - accuracy: 0.9800 - val_loss: 0.1605 - val_accuracy:

500/500 [==============================] - 0s 22us/step - loss: 0.0560 - accuracy: 0.9840 - val_loss: 0.1537 - val_accuracy: 0.9399
Epoch 449/500
500/500 [==============================] - 0s 17us/step - loss: 0.0565 - accuracy: 0.9840 - val_loss: 0.1566 - val_accuracy: 0.9399
Epoch 450/500
500/500 [==============================] - 0s 21us/step - loss: 0.0560 - accuracy: 0.9880 - val_loss: 0.1513 - val_accuracy: 0.9399
Epoch 451/500
500/500 [==============================] - 0s 20us/step - loss: 0.0556 - accuracy: 0.9860 - val_loss: 0.1613 - val_accuracy: 0.9419
Epoch 452/500
500/500 [==============================] - 0s 18us/step - loss: 0.0563 - accuracy: 0.9900 - val_loss: 0.1561 - val_accuracy: 0.9399
Epoch 453/500
500/500 [==============================] - 0s 19us/step - loss: 0.0570 - accuracy: 0.9820 - val_loss: 0.1560 - val_accuracy: 0.9419
Epoch 454/500
500/500 [==============================] - 0s 20us/step - loss: 0.0562 - accuracy: 0.9920 - val_loss: 0.1637 - val_accuracy:

In [9]:
[test_loss, test_acc] = model.evaluate(df_test, encoded_test)
print("Evaluation result on Test Data : Loss = {}, accuracy = {}".format(test_loss, test_acc))

499/499 [==============================] - 0s 34us/step
Evaluation result on Test Data : Loss = 0.15999835995371212, accuracy = 0.9378757476806641


In [10]:
import matplotlib.pyplot as plt

In [35]:
y_test= np.array(df_test['1'])


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [12]:
predicts = model.predict(df_test)

In [34]:
y_pred = (predicts > 0.5)
df_test

1  1.1  1.2  0.996078431372549  0.992156862745098  1.3       1.4  \
500  1  1.0  1.0                1.0                1.0  1.0  1.000000   
501  1  1.0  1.0                1.0                1.0  1.0  1.000000   
502  1  1.0  1.0                1.0                1.0  1.0  1.000000   
503  1  1.0  1.0                1.0                1.0  1.0  1.000000   
504  1  1.0  1.0                1.0                1.0  1.0  1.000000   
..  ..  ...  ...                ...                ...  ...       ...   
994  1  1.0  1.0                1.0                1.0  1.0  0.717647   
995  1  1.0  1.0                1.0                1.0  1.0  1.000000   
996  1  1.0  1.0                1.0                1.0  1.0  1.000000   
997  1  1.0  1.0                1.0                1.0  1.0  1.000000   
998  1  1.0  1.0                1.0                1.0  1.0  1.000000   

          1.5       1.6       1.7  ...  0.988235294117647.7     1.295  \
500  1.000000  1.000000  1.000000  ...             0.866667  1.000000   
501  1.000000  1.000000  1.000000  ...             1.000000  1.000000   
502  1.000000  1.000000  1.000000  ...             1.000000  1.000000   
503  1.000000  1.000000  1.000000  ...             0.776471  0.725490   
504  0.996078  1.000000  1.000000  ...             0.952941  1.000000   
..        ...       ...       ...  ...                  ...       ...   
994  0.313725  0.219608  0.976471  ...             0.305882  0.298039   
995  1.000000  1.000000  0.952941  ...             0.698039  1.000000   
996  1.000000  1.000000  1.000000  ...             1.000000  1.000000   
997  1.000000  1.000000  1.000000  ...             1.000000  1.000000   
998  1.000000  1.000000  1.000000  ...             1.000000  1.000000   

        1.296     1.297     1.298  0.996078431372549.11  1.299  1.300  1.301  \
500  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   
501  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   
502  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   
503  0.890196  1.000000  0.992157              1.000000    1.0    1.0    1.0   
504  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   
..        ...       ...       ...                   ...    ...    ...    ...   
994  0.274510  0.219608  0.243137              0.894118    1.0    1.0    1.0   
995  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   
996  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   
997  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   
998  1.000000  1.000000  1.000000              1.000000    1.0    1.0    1.0   

     1.302  
500    1.0  
501    1.0  
502    1.0  
503    1.0  
504    1.0  
..     ...  
994    1.0  
995    1.0  
996    1.0  
997    1.0  
998    1.0  

[499 rows x 784 columns]

In [24]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [36]:
matrix = confusion_matrix(encoded_test.argmax(axis=1), y_pred.argmax(axis=1))

In [38]:
print ('Confusion Matrix :')
print(matrix) 
print ('Accuracy Score :',accuracy_score(encoded_test.argmax(axis=1), y_pred.argmax(axis=1))) 
print ('Report : ')
print (classification_report(encoded_test.argmax(axis=1), y_pred.argmax(axis=1)))

Confusion Matrix :
[[ 83   0  13   0   2]
 [  0  88   3   0   0]
 [  2   1 100   0   2]
 [  0   0   0 103   0]
 [  3   0   3   1  95]]
Accuracy Score : 0.9398797595190381
Report : 
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        98
           1       0.99      0.97      0.98        91
           2       0.84      0.95      0.89       105
           3       0.99      1.00      1.00       103
           4       0.96      0.93      0.95       102

    accuracy                           0.94       499
   macro avg       0.94      0.94      0.94       499
weighted avg       0.94      0.94      0.94       499

